package view;

import controller.CacaNiquelController;
import exceptions.InvalidMapException;
import java.util.Map;
import java.util.TreeMap;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import model.IconGenerator;
import util.Constantes;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ETEC
 * 
 */
public class CacaNiquelView extends javax.swing.JFrame {

    private int moeda;
    private int pontos;
    private int i1;
    private int i2;
    private int i3;

    private boolean isValor1Concluido = Boolean.FALSE;
    private boolean isValor2Concluido = Boolean.FALSE;
    private boolean isValor3Concluido = Boolean.FALSE;

    private IconGenerator iconGenerator;
    private Map<Integer, ImageIcon> mapaIcones = new TreeMap<>();

    private CacaNiquelController cacaNiquelController = null;

    public CacaNiquelView() {

        initComponents();

        Map<Integer, ImageIcon> mapa = new TreeMap<>();

        try {

            this.cacaNiquelController = new CacaNiquelController(this);

            this.iconGenerator = new IconGenerator(cacaNiquelController.carregarMapaImagens(mapa));

            mapaIcones = iconGenerator.getMapaArquivosIcones();

            btnValor1.setIcon(mapaIcones.get(Constantes.IMAGEM_INICIAL));
            btnValor2.setIcon(mapaIcones.get(Constantes.IMAGEM_INICIAL));
            btnValor3.setIcon(mapaIcones.get(Constantes.IMAGEM_INICIAL));

        } catch (InvalidMapException ex) {

            JOptionPane.showMessageDialog(this, ex.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnValor1 = new javax.swing.JButton();
        btnValor2 = new javax.swing.JButton();
        btnValor3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbl_titulo_moeda = new javax.swing.JLabel();
        lbl_titulo_pontuacao = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnApostar = new javax.swing.JButton();
        btnJogar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("..:: CAÇA - NIQUEL ::..");
        setAlwaysOnTop(true);

        btnValor1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        btnValor1.setFocusPainted(false);
        btnValor1.setFocusable(false);
        btnValor1.setMaximumSize(new java.awt.Dimension(136, 129));
        btnValor1.setMinimumSize(new java.awt.Dimension(136, 129));
        btnValor1.setOpaque(true);
        btnValor1.setPreferredSize(new java.awt.Dimension(136, 129));
        btnValor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValor1ActionPerformed(evt);
            }
        });

        btnValor2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        btnValor2.setFocusPainted(false);
        btnValor2.setFocusable(false);
        btnValor2.setMaximumSize(new java.awt.Dimension(136, 129));
        btnValor2.setMinimumSize(new java.awt.Dimension(136, 129));
        btnValor2.setOpaque(true);
        btnValor2.setPreferredSize(new java.awt.Dimension(136, 129));
        btnValor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValor2ActionPerformed(evt);
            }
        });

        btnValor3.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        btnValor3.setFocusPainted(false);
        btnValor3.setFocusable(false);
        btnValor3.setMaximumSize(new java.awt.Dimension(136, 129));
        btnValor3.setMinimumSize(new java.awt.Dimension(136, 129));
        btnValor3.setOpaque(true);
        btnValor3.setPreferredSize(new java.awt.Dimension(136, 129));

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        lbl_titulo_moeda.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lbl_titulo_moeda.setText("Quantidade de Moedas:");

        lbl_titulo_pontuacao.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lbl_titulo_pontuacao.setText("Pontuação");

        jLabel4.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel4.setText("00");

        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel2.setText("00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_titulo_moeda, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_titulo_pontuacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_titulo_moeda)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_titulo_pontuacao)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );

        btnApostar.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        btnApostar.setText("Apostar");
        btnApostar.setEnabled(false);
        btnApostar.setMaximumSize(new java.awt.Dimension(160, 56));
        btnApostar.setMinimumSize(new java.awt.Dimension(160, 56));
        btnApostar.setPreferredSize(new java.awt.Dimension(160, 56));
        btnApostar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApostarActionPerformed(evt);
            }
        });

        btnJogar.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        btnJogar.setText("Novo Jogo");
        btnJogar.setMaximumSize(new java.awt.Dimension(160, 56));
        btnJogar.setMinimumSize(new java.awt.Dimension(160, 56));
        btnJogar.setPreferredSize(new java.awt.Dimension(160, 56));
        btnJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJogarActionPerformed(evt);
            }
        });

        btnSair.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        btnSair.setText("Sair");
        btnSair.setMaximumSize(new java.awt.Dimension(160, 56));
        btnSair.setMinimumSize(new java.awt.Dimension(160, 56));
        btnSair.setPreferredSize(new java.awt.Dimension(160, 56));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(btnValor2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnValor3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnApostar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnJogar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnValor2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnValor3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJogar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApostar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90))
        );

        setSize(new java.awt.Dimension(555, 451));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnApostarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApostarActionPerformed

        isValor1Concluido = Boolean.FALSE;
        isValor2Concluido = Boolean.FALSE;
        isValor3Concluido = Boolean.FALSE;

        cacaNiquelController.getThreadRodarBtn1().start();
        cacaNiquelController.getThreadRodarBtn2().start();
        cacaNiquelController.getThreadRodarBtn3().start();
        cacaNiquelController.getThreadChecarJogo().start();

    }//GEN-LAST:event_btnApostarActionPerformed

    private void btnJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJogarActionPerformed
        moeda = 20;
        pontos = 0;
        btnApostar.setEnabled(true);

        jLabel2.setText(String.valueOf(moeda));
        jLabel4.setText(String.valueOf(pontos));
    }//GEN-LAST:event_btnJogarActionPerformed

    private void btnValor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValor2ActionPerformed


    }//GEN-LAST:event_btnValor2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnValor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValor1ActionPerformed

    }//GEN-LAST:event_btnValor1ActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CacaNiquelView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CacaNiquelView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CacaNiquelView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CacaNiquelView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CacaNiquelView().setVisible(true);
            }
        });
    }

    public void atualizaImagemBotao(JButton botao, ImageIcon imagem) {

        botao.setIcon(imagem);
        botao.repaint();

    }

    public int getMoeda() {
        return moeda;
    }

    public int getPontos() {
        return pontos;
    }

    public void setMoeda(int moeda) {
        this.moeda = moeda;
    }

    public void setPontos(int pontos) {
        this.pontos = pontos;
    }

    public int getI1() {
        return i1;
    }

    public int getI2() {
        return i2;
    }

    public int getI3() {
        return i3;
    }

    public void setI1(int i1) {
        this.i1 = i1;
    }

    public void setI2(int i2) {
        this.i2 = i2;
    }

    public void setI3(int i3) {
        this.i3 = i3;
    }

    public boolean isIsValor1Concluido() {
        return isValor1Concluido;
    }

    public boolean isIsValor2Concluido() {
        return isValor2Concluido;
    }

    public boolean isIsValor3Concluido() {
        return isValor3Concluido;
    }

    public void setIsValor1Concluido(boolean isValor1Concluido) {
        this.isValor1Concluido = isValor1Concluido;
    }

    public void setIsValor2Concluido(boolean isValor2Concluido) {
        this.isValor2Concluido = isValor2Concluido;
    }

    public void setIsValor3Concluido(boolean isValor3Concluido) {
        this.isValor3Concluido = isValor3Concluido;
    }

    public IconGenerator getIconGenerator() {
        return iconGenerator;
    }

    public JButton getBtnValor1() {
        return btnValor1;
    }

    public JButton getBtnValor2() {
        return btnValor2;
    }

    public JButton getBtnValor3() {
        return btnValor3;
    }

    public void exibirPontuacao() {

        jLabel2.setText(moeda + "");
        jLabel4.setText(pontos + "");
    }

    public void habilitarBotoes(boolean habilitar) {

        btnApostar.setEnabled(habilitar);
        btnJogar.setEnabled(habilitar);
        btnSair.setEnabled(habilitar);
        btnValor1.setEnabled(habilitar);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApostar;
    private javax.swing.JButton btnJogar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnValor1;
    private javax.swing.JButton btnValor2;
    private javax.swing.JButton btnValor3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_titulo_moeda;
    private javax.swing.JLabel lbl_titulo_pontuacao;
    // End of variables declaration//GEN-END:variables
}
